---
title: "Moxi PK Model - Final"
author: "Arnay Garhyan"
date: "2024-07-14"
output:
  html_document:
    theme: cerulean
    toc: yes
    toc_float: no
    code_folding: hide
    number_sections: yes
    df_print: paged
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, collapse = T, fig.width = 10, fig.height = 6)
pander::panderOptions('table.style', 'rmarkdown')
pander::panderOptions('table.split.table', Inf)
options(knitr.table.format = 'markdown')
```

```{r, message=FALSE}
if (!require(pacman)) install.packages("pacman")
suppressPackageStartupMessages(pacman::p_load(
  tidyverse,
  ggplot2,
  zoo, 
  table1,
  minpack.lm,
  broom,
  nlmixr2,
  pander,
  cowplot,
  kableExtra,
  tidyvpc,
  rxode2,
  shiny,
  bslib,
  rxode2
  ))
```

```{r}
#source("../Compartment_Models.R", chdir=TRUE)
source("../Model_Report_Functions.R", chdir=TRUE)
source("../Moxi_PKPD.R", chdir=TRUE)
```



```{r}
recreate_fit<-F

dataset_no_vomit <- get_pk_dataset(F,T) # later occ, remove vomit
dataset_full <- get_pk_dataset(F,F)

dataset_name <- dataset_no_vomit


model_name <- "moxi_one_compartment"
model_function <- one.compartment.proportional # taken from Moxi_PKPD.R

model_file_name <- paste(model_name,".RData",sep="")
if (recreate_fit || !file.exists(file = model_file_name)){
  fit_used <- nlmixr2(model_function, data = dataset_name,  est="focei", table=tableControl(keep = c('SEX', 'WT')), foceiControl(print=0))
  save(fit_used, file=model_file_name)
} else {
  load(model_file_name)
}
```


``` {r}
final_model <- function(){
  ini({
    tka <- fix(log(0.7630404)); label("Ka")
    tcl <- fix(log(3.2363909)); label("Cl")
    tv <- fix(log(33.9763030)); label("V")
    
    covka <- fix(-0.2138061)
    allcl <- fix(1.0050231)
    allv <- fix(1.0000000)
    
    eta.ka ~ fix(0.2676694)
    eta.cl + eta.v ~ fix(c(0.04400711, 0.02083013, 0.01501074))
    
    prop.sd <- fix(0.2756416)
  })
  
  model({
    WTMED <- 3.5-3.5
    WTALOM <- 3.5/3.5
    
    ka <- exp(tka + eta.ka + (covka*WTMED))
    
    cl <- exp(tcl + eta.cl + allcl*log(WTALOM))
    v <- exp(tv + eta.v + allv*log(WTALOM))
    
    d/dt(depot) <- -ka * depot
    d/dt(center) <- ka * depot - (cl / v) * center
    
    cp <- center / v
    cp ~ prop(prop.sd)
  })
}

final_nlmixr_model <- final_model

final_model <- rxode(final_model)
final_model <- final_model$simulationModel

final_omegas <- lotri::lotri({
  eta.ka ~ 0.2676694
  eta.cl + eta.v ~ c(0.04400711, 0.02083013, 0.01501074)
})



make_pk_plot <- function(wt, dose){
  #dose = mg/kg
  ev  <- et(amountUnits="mg", timeUnits="hours") %>% 
    et(amt=dose*wt*1000, cmt="depot") %>%
    et(0:100) %>%
    et(id=1:100)
  
  set.seed(10)
  rxSetSeed(10)
  
  cov_df <- data.frame(id=1:200,WT=rnorm(200,wt,0.8797681))
  cov_df <- cov_df %>% filter(WT>2.5 & WT<8.5)
  cov_df <- cov_df[sample(nrow(cov_df), 100),]
  cov_df$id <- 1:100
  
  cov_df$WTMED <- cov_df$WT-3.5
  cov_df$WTALOM <- cov_df$WT/3.5
  
  
  sim <- rxSolve(final_model, ev, 
                 omega=final_omegas, 
                 #params = params_wt, 
                 nSub=100,
                 iCov=cov_df)
  return(
    ggplot(data=sim,aes(x=time,y=cp, group=id))+
    geom_line(alpha=.2, linewidth=1) +
    scale_y_log10(limits=c(1,100000))
    )
}
```


```{r}
watson_data <- read.csv("watson_paper_dataset.csv")
watson_data$PREV_DOSE <- na.locf(watson_data$AMT, na.rm = FALSE)

mean_weight <- 3.15 #or 4.45 for male


dose <- 90
inData <- watson_data %>% filter(watson_data$PREV_DOSE==90000)
plot_90_f <- make_pk_plot(mean_weight,dose)

for (id in 1:16){
  plot_90_f <- plot_90_f +
      geom_point(data = inData %>% filter(ID==id), inherit.aes = F, aes(x=TIME,y=DV), color="red")
}

dose <- 30
inData <- watson_data %>% filter(watson_data$PREV_DOSE==30000)
plot_30_f <- make_pk_plot(mean_weight,dose)

for (id in 1:16){
  plot_30_f <- plot_30_f +
      geom_point(data = inData %>% filter(ID==id), inherit.aes = F, aes(x=TIME,y=DV), color="red")
}

dose <- 10
inData <- watson_data %>% filter(watson_data$PREV_DOSE==10000)
plot_10_f <- make_pk_plot(mean_weight,dose)

for (id in 1:16){
  plot_10_f <- plot_10_f +
      geom_point(data = inData %>% filter(ID==id), inherit.aes = F, aes(x=TIME,y=DV), color="red")
}


mean_weight <- 4.45
dose <- 90
inData <- watson_data %>% filter(watson_data$PREV_DOSE==90000)
plot_90_m <- make_pk_plot(mean_weight,dose)

for (id in 1:16){
  plot_90_m <- plot_90_m +
      geom_point(data = inData %>% filter(ID==id), inherit.aes = F, aes(x=TIME,y=DV), color="red")
}

dose <- 30
inData <- watson_data %>% filter(watson_data$PREV_DOSE==30000)
plot_30_m <- make_pk_plot(mean_weight,dose)

for (id in 1:16){
  plot_30_m <- plot_30_m +
      geom_point(data = inData %>% filter(ID==id), inherit.aes = F, aes(x=TIME,y=DV), color="red")
}

dose <- 10
inData <- watson_data %>% filter(watson_data$PREV_DOSE==10000)
plot_10_m <- make_pk_plot(mean_weight,dose)

for (id in 1:16){
  plot_10_m <- plot_10_m +
      geom_point(data = inData %>% filter(ID==id), inherit.aes = F, aes(x=TIME,y=DV), color="red")
}

mean_weight <- 5.25
dose <- 10
plot_10_Holzgrefe <- make_pk_plot(mean_weight,dose) +
  geom_point(inherit.aes = F, aes(x=4,y=.05*1000), color="red") +
  geom_point(inherit.aes = F, aes(x=4,y=1.01*1000), color="red") +
  geom_point(inherit.aes = F, aes(x=4,y=1.37*1000), color="red")

mean_weight <- 5.25
dose <- 50
plot_50_Holzgrefe <- make_pk_plot(mean_weight,dose) +
  geom_point(inherit.aes = F, aes(x=4,y=5.05*1000), color="red") +
  geom_point(inherit.aes = F, aes(x=4,y=5.86*1000), color="red") +
  geom_point(inherit.aes = F, aes(x=4,y=8.23*1000), color="red")


```

# Watson Datapoints Overlayed on Simulation {.tabset}

## Females {.tabset}

### 10 mg/kg Dose {.tabset}
```{r}
plot_10_f
```

### 30 mg/kg Dose {.tabset}
```{r}
plot_30_f
```

### 90 mg/kg Dose {.tabset}
```{r}
plot_90_f
```


## Males {.tabset}

### 10 mg/kg Dose {.tabset}
```{r}
plot_10_m
```

### 30 mg/kg Dose {.tabset}
```{r}
plot_30_m
```

### 90 mg/kg Dose {.tabset}
```{r}
plot_90_m
```

# Holzgrefe Datapoints Overlayed on Simulation {.tabset}

## 10 mg/kg Dose {.tabset}
```{r}
plot_10_Holzgrefe
```

## 50 mg/kg Dose {.tabset}
```{r}
plot_50_Holzgrefe
```
